---
- name: Build Maven Project, Build Docker Image, and Push to Docker Hub
  hosts: localhost
  become: yes
  vars:
    project_directory: "/home/dele/oyedeloy-DevOpsClassCodes"
    local_image_name: "my-java-app"
    local_image_tag: "01"
    dockerhub_credentials_file: "/home/dele/dockerhub_credentials.yml"  # Name of your Ansible Vault file

  tasks:
    - name: Load Docker Hub Credentials
      ansible.builtin.include_vars:
        file: "{{ dockerhub_credentials_file }}"
      vars:
        ansible_become: false  # Prevent becoming root for this task

    - name: Change to the project directory
      shell: cd "{{ project_directory }}"
      args:
        chdir: "{{ project_directory }}"

    - name: Execute Maven Build Steps
      shell: "mvn {{ item }}"
      args:
        chdir: "{{ project_directory }}"
      loop:
        - compile
        - test
        - pmd:pmd
        - package

    - name: Build Docker Image Locally
      shell: |
        docker build -t "{{ local_image_name }}:{{ local_image_tag }}" -f Dockerfile "{{ project_directory }}"
      delegate_to: localhost

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker Image to Docker Hub
      docker_image:
        name: "{{ local_image_name }}:{{ local_image_tag }}"
        push: yes
