---
- name: Install Python 3 and Docker on Ubuntu
  hosts: all  # Use the host alias defined in your SSH config
  become: yes  # Enable privilege escalation

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - docker.io

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
