---
# Execute Maven Build Steps, and Save JAR File Locally

- name: Execute Maven Build Steps
  hosts: localhost   # Replace with the hostname or group of hosts where you want to run the build
  become: yes                 # If you need elevated privileges, set to 'yes' and provide sudo password
  vars:
    project_directory: "/home/dele/oyedeloy-DevOpsClassCodes"
    your_username: "root"
  tasks:
    - name: Change to the project directory
      become_user: "{{ your_username }}" # Replace with your username
      shell: cd "{{ project_directory }}"
      args:
        chdir: "{{ project_directory }}"

    - name: Execute Maven Build Steps
      become_user: "{{ your_username }}"  # Replace with your username
      shell: "mvn {{ item }}"
      args:
        chdir: "{{ project_directory }}"
      loop:
        - compile
        - test
        - pmd:pmd
        - package

    - name: Copy JAR file to local directory
      become_user: your_username  # Replace with your username
      copy:
        src: "/home/dele/oyedeloy-DevOpsClassCodes/target/addressbook.war"  # Path to the generated JAR file
        dest: "/home/dele/oyedeloy-DevOpsClassCodes/addressbook.war"  # Local directory where you want to save the JAR file
